//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `AStockService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.astock;

/** @hidden */
public class _AStockServicePrxI extends com.zeroc.Ice._ObjectPrxI implements AStockServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
